In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.43657482, -1.49084165,  0.66794267,  0.10625123, -0.20773059,
       -0.2658493 , -0.4946428 ,  0.03700335, -1.25466294, -0.42948667])

In [7]:
B = np.random.randn(10)
B

array([-1.93777448,  0.59818266, -1.76383544,  1.60289683,  1.44104542,
        1.13884916, -0.75662703, -0.41427559, -0.29211873, -1.3075021 ])

In [8]:
# Binary Functions
np.add(A,B)

array([-2.37434931, -0.892659  , -1.09589277,  1.70914806,  1.23331482,
        0.87299986, -1.25126984, -0.37727224, -1.54678167, -1.73698877])

In [9]:
np.maximum(A,B)

array([-0.43657482,  0.59818266,  0.66794267,  1.60289683,  1.44104542,
        1.13884916, -0.4946428 ,  0.03700335, -0.29211873, -0.42948667])

In [10]:
np.max(B)

1.6028968321272465

In [12]:
np.square(A,B)

array([1.90597577e-01, 2.22260883e+00, 4.46147407e-01, 1.12893242e-02,
       4.31520000e-02, 7.06758485e-02, 2.44671503e-01, 1.36924759e-03,
       1.57417909e+00, 1.84458798e-01])