In [2]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray', arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [8]:
arr2 = arr

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez('ziparray.npz', x = arr1, y = arr2)

In [11]:
archive_array = np.load('ziparray.npz')

In [12]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [13]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.savetxt('mytextarray.txt', arr, delimiter = ',')

In [23]:
arr = np.loadtxt('mytextarray.txt', delimiter = ',')

In [24]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])