In [2]:
import numpy as np

In [3]:
5/2

2.5

In [16]:
arr1= np.array([[1,2,3,4],[8,9,10,11]])

In [17]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [18]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [19]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])